### ISSUE TITLE
Compilation error after upgrade to v0.6.2

### ISSUE THREAD

**Issue by nsine** [ardatan/graphql-toolkit#302]
Hey guys 👋

Recently we upgraded `graphql-toolkit` version from 0.5.18 to 0.6.2. And now when compiling our Typescript project I see the next error:
```
../../node_modules/@graphql-toolkit/url-loader/dist/esnext/load-from-url.d.ts(2,31): error TS2304: Cannot find name 'WindowOrWorkerGlobalScope'.
```

Node v12.3.1
Typescript v3.6.4

**Comment by ardatan** [comment]
@nsine Could you try it with `0.6.5-alpha-b454c32.5+b454c32` canary version?

**Comment by ardatan** [comment]
Fixed in 0.6.5!

**Comment by nsine** [comment]
thanks for the quick update!
seems to be fixed 🎉🎉
